### ISSUE TITLE
Duplicated names

### ISSUE THREAD

**Issue by adomingues** [rstacruz/kingraph#1]
I am making my family tree, and `kingraph` is a great tool for the job. I am having some problems with Duplicate names though: Both my father and I share the First name, so I end married to my mother, which is weird :)

Is there a way to resolve this without resorting to using my middle name? This also an problem in that YAML will not allow names with spaces (I think). For instance:

```YAML
people:
  Antonio Miguel:
    name:  Antonio Miguel
    fullname: Antonio Miguel de Jesus Domingues
    gender: m 
```

Cheers.

**Comment by adomingues** [comment]
> This also an problem in that YAML will not allow names with spaces (I think)

I thought wrong: YAML does allow something like:

```YAML
    parents: [Antonio, Graciete]
    children: [Antonio Miguel, Catarina]
```
The point about duplicated still stands, since this is common in large families. Probably unsolvable, but I will leave it here nonetheless.

**Comment by rstacruz** [comment]
oh hey, sorry this took a while. spaces are fine. You can indeed use spaces as the person's ID.

```yml
families:
  - parents: [John, Susan]
    children: [John II, Susan II]

people:
  John:
    name: John
    fullname: John Marks
  John II:
    name: John
    fullname: John Marks
```

how you choose your ID's is up to you; sometimes a middle name (or initial) would be necessary to disambiguate.
