### ISSUE TITLE
Sibling(children) order are jumbled because of subfamilies

### ISSUE THREAD

**Issue by gppam** [rstacruz/kingraph#9]
Hi, loving your project! But I've encountered this specific problem. For example below, Bill is the eldest but he is put below the youngest sibling Ginny, because he has family. Is there a fix for this?

![weasleyfam](https://user-images.githubusercontent.com/14272390/50293188-f3581480-04ad-11e9-94a4-0047f545c29a.png)

```
families:
  - parents: [Arthur, Molly]
    children: [Ginny, Ron, George, Fred, George, Percy, Charlie, Bill]
    families:
      - parents: [Bill, Fleur]
        children: [Victoire, Dominique, Louis]
      - parents: [George, Angelina]
      - parents: [Ron, Hermione]
        children: [Rose, Hugo]
```

An inelegant solution I did was to make the single sibling a `parent` but that's not what it's supposed to do.
